### ISSUE TITLE
Correspondence Between Center and DICOM

### ISSUE THREAD

**Issue by mpahuta** [mathiasunberath/DeepDRR#15]
Hi

I've downloaded ABD_LYMPH_057 from the NIH database and am using it in DeepDRR. I'm trying to put the isocenter in a specific location. I've opened the DICOM in 3D Slicer, and the location is at axial cut -433.800mm, sagittal 5.078mm, and coronal 144.111mm. I've been unsuccessful in rationally changing the center vector in the DeepDRR code to effect this change... 

I'm trying to understand what the relationship is between the slices and the origin. I've gone over your [Anatomical Landmarks](https://github.com/mathiasunberath/AnatomicalLandmarks) work.., I don't understand how you computed the Origin Offset?

I would greatly appreciate some guidance...

**Comment by mathiasunberath** [comment]
Can you please provide information on what you have tried in DeepDRR and what you are seeing. First thing I would suggest is to load the volume and not change the origin. If the CT was read correctly, DeepDRR should position it such that the center voxel is zero-centered, i.e. the origin of rotation of the camera. This means that not doing anything should generate an image. Can you verify this? If not, please describe the steps you are taking in DeepDRR. Thanks.

**Comment by mpahuta** [comment]
Hi,

Yes, I am obtaining a centered image with the default origin.

I this correct?
- the default origin would be the central point in the [image coordinate system](https://www.slicer.org/wiki/Coordinate_systems)
- changing the default image center translates the center in the ijk coordinate system described in the web page

**Comment by gaocong13** [comment]
The [Anatomical Landmarks repo](https://github.com/mathiasunberath/AnatomicalLandmarks) is a demonstration to use our 3D landmark annotations. If you just want to manipulate the origin, the best practical way for you to get familiarize is to hard code some offsets in [line 86](https://github.com/mathiasunberath/DeepDRR/blob/f8781aa57dc3ac9f823a28d107825de9574c6df8/example_projector.py#L86) so that you can validate whether it coincides with your coordinate definition assumption.
