### ISSUE TITLE
DRR for cheat CT

### ISSUE THREAD

**Issue by pengchengu** [mathiasunberath/DeepDRR#2]
Hi,
I tried DeepDRR  fort cheat CT and i found the lung area is very bright (Figure 1 and Figure 2) compared to real x-ray (Figure 3), so it's difficult to observe the shape of vertebrae.  I found in the code of materials, there are specific Attenuation Coefficients for the lung. So do i have to segment the lung first, if I want to observe thoracic vertebra in DRR.
**Figure 1**
![screenshot from 2018-11-30 14-43-41](https://user-images.githubusercontent.com/15112536/49273104-dcc22d00-f4ae-11e8-9dc9-9c64dd306f61.png)
**Figure 2**
![screenshot from 2018-11-30 14-44-59](https://user-images.githubusercontent.com/15112536/49273106-de8bf080-f4ae-11e8-8b00-69d5387787db.png)
**Figure 3**
![screenshot from 2018-11-30 15-07-01](https://user-images.githubusercontent.com/15112536/49273983-b3ef6700-f4b1-11e8-9ac5-b6e2239f7a61.png)

**Comment by mathiasunberath** [comment]
Hi, 
I have some questions and suggestions. 
1) Which segmentation algorithm are you using? V-net or threshold based? Have you investigated whether the segmentation algorithm into bone-soft tissue-air gives you the expected result? If not, try to look at that and then I would suggest playing with the threshold parameters. It might be that your dataset has some global linear intensity transformation such that segmentation is wrong (and consequently also densities, materials, etc). 
2) If segmentation is correct, then it may be a difference in geometry: patient prone vs supine.
3) Are you using scatter generation? If yes, try switching off. The images a system will give you will never be the acquired image but will have passed through many pre-processing steps that bring the image quality to what you see there.
4) Your CT seems to have somewhat low resolution, maybe you want to try with higher resolution CT to get better outcome. Low resolution in 3D will be amplified due to magnification during projection. 

@Jan-Nico anything to add?

Let us know how it goes.
Mathias

**Comment by pengchengu** [comment]
Hi,
Thanks for the suggestions.
1. The segmentation algorithm is threshold based and i have checked the segmentation results are correct with the help of 3D Slicer.
2. Both DRR and real x-ray are patient prone
3. The former results used scatter generation and  now i switched off that, the result is showed in Figure 4.
4.  Figure 1 is the result of a CT with (0.488mm,0.488mm,1.5 mm) voxel size. Figure 2, 3 and 4 are from a CT with(0.869mm，0.869mm，1.000mm). I believe the resolutions of both CT are eligible for DRR.

From the results, I believe switched off the scatter generation do help reducing the brightness of lung area, but it is still quite different from the real x-ray. I'm trying to put a scale weight on the Attenuation Coefficients of air to reduce the brightness of lung, is that feasible method? Besides, what's the meaning of the pixel value of the DRR result, how can i normalized it to the same distribution of real x-ray for the following deep learning model?
Figure 4
![image](https://user-images.githubusercontent.com/15112536/49363914-e2717a00-f71d-11e8-98ed-b586d1b675f3.png)

**Comment by mathiasunberath** [comment]
Hi. 
It is difficult to remote debug what may be the case, again some more comments.
I personally think we should be more interested in achieving the same image appearance rather than the fact that "the lungs are bright". This may be due to different proportions in the anatomy so this does not seem to be a good indicator to me. 

1) I assume that you have gotten the above "real" X-ray directly from a scanner which (as mentioned previously) will have gone through a pre-processing pipeline. As a consequence, direct comparison of these images will be difficult if you do not know what processing is applied to the other images. 
2) That being said, some other properties may be different (I assume that indeed the segmentation is correct): Which spectrum are you using? Is it comparable (kVp and filtration) to the spectrum used to generate the real images?
3) It seems to me that the DRRs are not, in fact, from the same prone position? When I compare the heart's outline, it seems to me that the apex is towards the right in your real X-ray and towards the left in  your generated images. 
4) Regarding your question for normalization: Off the top of my head, we compute the deposited energy per pixel. However, for processing in a NN you may want to normalize to -1,1 or so anyway, so maybe that does not make a big difference.
5) Regarding the image resolution: You are considering a rather high magnification view onto your anatomy with magnification factors likely around 2 for the spine. This will increase the artifacts due to low resolution on your detector which will also add to then not-as-natural image appearance. 

As a side remark, you are obviously free to tune any parameter that you like, but I would discourage the heuristic adjustment of any attenuation coefficients etc before having identified the source of error. It currently seems to me that the largest difference in appearance of the images is bone contour contrast which could be due to a different source spectrum and processing.

**Comment by mathiasunberath** [comment]
I will close this issue for now since there was no more response. Let us know if you have further questions.
