### ISSUE TITLE
meaningless output of a new dicom dataset

### ISSUE THREAD

**Issue by hoda213** [mathiasunberath/DeepDRR#21]
Hello,
I have ran the example_projector code with the default dataset properly.but now I want to load our experimental dataset which contains 128 2d dicoms with the size of  512x512. It doesn't have any technical error but the output is meaningless and without any segmentation.Which part should I change?
In addition,  I also like to know that how can I switch the output from transvers plane to frontal.

Thanks in advance,
Hoda

**Comment by gaocong13** [comment]
Hi hoda,

I would suggest you first check the correctness of your volume load and voxel size in the file 'load_dicom.py'. You need to make sure all of your dicom slices are correctly loaded. Then you could first try debugging using the thresholding segmentation method 'load_dicom.py/conv_hu_to_materials_thresholding()'. Because our segmentation network is trained on a specific dataset, this could lead to biased output if your image domain is very different.

Considering switching the output from transvers plane to frontal, please check the volume projection geometry under 'projection_matrix.py'. You can specify the rotation matrix to achieve arbitrary perspectives.
