### ISSUE TITLE
Problem with generated output images

### ISSUE THREAD

**Issue by sainatarajan** [mathiasunberath/DeepDRR#7]
We tried to run the DeepDRR after solving some of the issues which I had posted earlier. The library was able to read our Dicom data successfully and also fills the volume with information. Some of the generated images that showed on the command-line after the segmentation network got loaded are:
![image1](https://user-images.githubusercontent.com/22982857/61939503-0b969180-afb1-11e9-91e5-b3853f11a024.png)

![image2](https://user-images.githubusercontent.com/22982857/61939510-0f2a1880-afb1-11e9-80f8-a3a994ca4bc1.png)

We have used the default camera settings of 2x2 binning. The problem is that, once all the spectral bins are evaluated, the program produces a blank white image on the screen, similar to this:

![image4](https://user-images.githubusercontent.com/22982857/61939611-46002e80-afb1-11e9-86db-03d45269ed24.png)

We also looked inside the generated_data folder, and unfortunately, the program has generated around 6 completely black tiff image files. Here is a sample output:

![black](https://user-images.githubusercontent.com/22982857/61939666-64662a00-afb1-11e9-8d7d-fb23738e316f.png)

Can you tell why the program has produced such outputs and where are we exactly going wrong?

**Comment by mathiasunberath** [comment]
Here are some pointers you may want to check:
- Have you inspected the volume's origin? It may be that the volume is physically located outside the imaged volume.
- Have you inspected the volume's spacing? We observed that some dicom formats are incompatible with the current reader (e.g. because they are proprietary), which may lead to the spacing to be 0.0. In this case, there will never be an intersection between the rays and the volume.
- Have you inspected your HU values after reading the volume? If there is a shift in HU that is unaccounted for, the volume may be too dense and all photons are attenuated.

Let us know how things go so that we can hopefully close the issue.

**Comment by sandorkonya** [comment]
Hi @mathiasunberath ,

thank you, the problem was the volume's spacing... which was not present in the DICOM header. Now we (with @sainatarajan ) are getting some results, surely we need further finetuning.
![Capture](https://user-images.githubusercontent.com/6852967/62368406-cb915a80-b52c-11e9-9b52-0f2ecc97d1b6.JPG)

For those who are facing the same problem, a possible solution to add the SliceThicnkess tag to all files:

```
from glob import glob
import pydicom
images = sorted(glob('yourpath_to_the_images/*.dcm'))

sliceloc =[]

for image in images:
    ds = pydicom.dcmread(image)
    sliceloc.append(ds.get('SliceLocation', "(missing)"))

sliceloc = sorted(sliceloc, key=int)
thickness = round(abs(sliceloc[1]-sliceloc[0]),2)
print(thickness)

for image in images:
    ds = pydicom.dcmread(image)
    ds.SliceThickness=thickness
    ds.save_as(image)
    print(image + " ....... saved\n")
```

**Comment by mathiasunberath** [comment]
Great to see this did it for you. Fine tuning will certainly be needed. I would suggest you start experimenting with threshold-based segmentation to better understand the effect all components have. As per discussions in other issues, you will likely want to inspect the log-transformed versions of your images to reduce the dynamic range.
