### ISSUE TITLE
Which settings to change - and how - for better images res.?

### ISSUE THREAD

**Issue by Turnman** [mathiasunberath/DeepDRR#8]
Hi Mathias,

thank you very much for providing the framework! 

I created some images from a perpendicular view on the pelvic are with your camera settings described in the paper using threshold segmentation, SPECTRUM120KV_AL43 and **no** scatter. See Fig. 1 (`origin=[0, 0, 120]`)

Then I moved up to the thorax by translation of the origin (`origin=[0, -180, -120]`) but am receiving a worse image. See Fig. 2
I might guess I could change by tweaking  the exposure - how could I do that?

Or do you have other suggestions? 

Thanks in advance! 

---
![image](https://user-images.githubusercontent.com/17703667/63472589-81aedc80-c427-11e9-91d0-882749ea19bd.png)

Fig. 1

---
![image](https://user-images.githubusercontent.com/17703667/63472541-56c48880-c427-11e9-802d-ae2396363c9f.png)

Fig. 2

**Comment by mathiasunberath** [comment]
Thank you for your interest in using DeepDRR. 

From the images you show, I am not sure I can fully understand the issue you are having. The second image you provide seems to cover the lumbar spine and some parts of the thorax, so this seems to be fine? You would expect decreased contrast due to the different proportion of soft-tissue and bone compared to the pelvic region. 

Here are some things to consider as pointers for further discussion.
- At this point, I would suggest you use threshold-based material decomposition and fine-tune the thresholds such that you obtain a good material decomposition in 3D. Doing this first will identify potential issues with automatic segmentation or incorrect thresholds. 
- You may want to play with the window/level to see whether the signal you expect to see is, in fact, there but with limited contrast due to the high dynamic range. 

Let me know whether this helps and if the issue can be closed.

**Comment by Turnman** [comment]
Thanks for the fast reply! 

- I'm currently using threshold-based segmentation which you mean with material decomposition, or?
- yes, I'd expect either a more detailed view of the vertebra or - as I 'moved' the origin downwards - a more detailed view of the ribs

To your pointers:
* fine-tuning thresholds: I'd probably start testing some HU values for my volume in e.g. Slicer and then set those in `conv_hu_to_materials_thresholding` to check, right?
* what do you mean by window/level?

Thank you very much for your advice!

**Comment by mathiasunberath** [comment]
- Yes, I mean threshold-based segmentation (since this segments different materials in the CT, I also refer to it as material decomposition; this is what we need it for anyways).
- As per my previous comment, this is to be expected. The ratio between soft-tissue and bone changes dramatically. Also, you will encounter differences when you investigate supine vs. prone patient position.

- Yes, fine tuning in slicer and then setting them there sounds good.
- Window/level: https://www.magnetic-resonance.org/ch/09-06.html
